services:
  db:
    image: mysql:8.0
    container_name: RateMyMajorDatabase
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: ratemymajor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ratemymajor_db_data:/var/lib/mysql

volumes:
  ratemymajor_db_data:
